services:
   nginx:
      image: nginx
      volumes:
         - ./nginx:/etc/nginx/conf.d
      ports:
         - "80:80"

   back-end:
      build:
        context: .
        dockerfile: Dockerfile
      expose:
         - "8000"
      deploy:
         resources:
            limits:
               cpus: "4"